//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDongHo.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class B_ShopEntities : DbContext
    {
        public B_ShopEntities()
            : base("name=B_ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand_2119110295> Brand_2119110295 { get; set; }
        public virtual DbSet<Category_2119110295> Category_2119110295 { get; set; }
        public virtual DbSet<Order_2119110295> Order_2119110295 { get; set; }
        public virtual DbSet<Product_2119110295> Product_2119110295 { get; set; }
        public virtual DbSet<Users_2119110295> Users_2119110295 { get; set; }
        public virtual DbSet<OrderDetail_2119110295> OrderDetail_2119110295 { get; set; }
    }
}
