//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDongHo.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_2119110295
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceDiscount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Slug { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> ShowOnHomePage { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> ArticleNumber { get; set; }
        public string Guarantee { get; set; }
        public string DeliveryTime { get; set; }
        public string Availabilty { get; set; }
        public string Trademark { get; set; }
        public string ProductNumber { get; set; }
        public string Origin { get; set; }
        public string Machine { get; set; }
        public string DialThickness { get; set; }
        public string Dial_Diameter { get; set; }
        public string Glasses { get; set; }
        public string Strap { get; set; }
        public Nullable<int> WaterProof { get; set; }
        public string Especially { get; set; }
        public string Avatar1 { get; set; }
        public string Avatar2 { get; set; }
        public string Avatar3 { get; set; }
        public string Avatar4 { get; set; }
    }
}
